language: c++
os: osx
osx_image: xcode8
xcode_project: Builds/MacOSX/MIDI2LR.xcodeproj
xcode_scheme: Release
branches:
  only:
  - master
  - coverity_scan
env:
  global:
   - LANG="en_US.UTF-8"
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "AlEDjB8lr2I5ce20A+FTTnM93h2Vv4L+wE+Enr+WT08VX68iYoHE6/yNlCJdkgUEoOsF2pPAcA1qdVYr9BOFr7BTG0r5Kk+kuJf8Ypyk2wJvsVvVPPicoSUY+2eXXluJ5ZOOSwaJ0a16wbxZH8L9JZWlXIZfI61BWFqbWaEpEL1EflUWZK7Uze1BBVGqtAfkuG3kO85dRgJ/fIFK5Z8dYN2nju3JqSC5j1kENPHywPW3uutxgHZjexc8tZOh2CoiweLCpC6Yg8Bc20/UGogCwWkNcTr9cLdV16qs4ftDXpoLOwVghSWGkAoaxcylQkJDIq6/t+9B57rOoiucIhfN/9JT1Y42rIuzKXkc59uWycfO86I2UVuOk6/0X7IE4q9hK4Sfz2SyagYZQ3nqsD6ovdBL9ZLs5teJT8iDipGpVVzb9swUHYTO8RyXKhMRNmvjHO+amVQrB/rc5Icwkgl52mqOmB8ZxEaG6DYY4rwmUqlM2jmZTcia2L+lbW/N6FWwyeObyy7GQcFH8UWUOMnq+OhLZu7uyU+aUZSL3ZipuVF+4Bh0YOgevj1gWhPwfMDSfaToG8YobT6GvcekMSPlvRHUTo/7J5PlJffgI4DCXI8u4hUneh7PtdGL6WzpU8cncBjWCzz2E31PPNerSYpPv/CVw1/jHCFgwoKwckxi2Fw="

addons:
  coverity_scan:
    project:
      name: "rsjaffe/MIDI2LR"
      description: "Build submitted via Travis CI"
    notification_email: rsjaffe@gmail.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
